rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.8
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - rbx-2
  - ree
  - jruby-18mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: 2.2.10
    - rvm: 2.1.8
    - rvm: 2.0.0
    - rvm: 1.9.3
    - rvm: 1.8.7
    - rvm: ree
    - rvm: jruby-18mode
    - rvm: jruby-19mode
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y postgresql-server-dev-all
